[package]
name = "fdlimit"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
license = "GPL"
exclude = [
    ".idea/*",
]
description = "Utility crate for raising file descriptors limit for OSX and Linux"

[dependencies]
libc = "0.2"